apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
spec:
  selector:
    matchLabels:
      app: homework
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: homework
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3000
