apiVersion: v1
kind: Service
metadata:
  name: homework-service
spec:
  selector:
    app: homework
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  # clusterIP: ??去哪里找，如何设置？ 答：不用找，在没自定义的情况下系统会自动分配
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127